# Site settings
title: Sykes Pro # site title
description: >- # site description
  He's writing about web technology and experience as a journal 
  for documentation of things that he learned, meet him <a href="https://github.com/sykespro" target="_blank" rel="noopener">@github</a>.
lang: en-US # default lang
timezone: America/New_York # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/sykespro/sykespro-personal # site repo [optional]
mode: light # default theme "dark" | "light"

# Profile settings
author:
  name: Daniel Sykes # author name
  bio: >- # tell to the world - Thinking Creatively | Planning Strategically | Executing Passionately
    Strategic, results-driven technical leader that enjoys kayak fishing and good scotch.
  username: sykespro # social media username eg. github, twitter 
  email: daniel@sykespro.com # your contact adress
  avatar: /assets/img/avatar.jpg # change with your own avatar

# Url settings
url: "https://sykespro.com"
baseurl:
permalink: /:title/
google_analytics:
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
